cat >app/emo_engine/persona/constants/labels.py<< EOF
#app/emo_engine/persona/constants/labels.py
from typing import Dict

EMO_LABEL_MAP: Dict[str, str] = {
    # ─── Dimensions ───────────────────────────────────────────
    "valence":           "Positive-Mood",
    "arousal":           "Physiologically Aroused",
    "energy":            "⚡ Energised",
    "fatigue":           "🥱 Fatigued",
    "dominance":         "Dominant",

    # ─── Primary emotions ────────────────────────────────────
    "joy":               "😊 Happy",
    "sadness":           "😢 Sad",
    "anger":             "😠 Angry",
    "fear":              "😨 Afraid",
    "disgust":           "🤢 Disgusted",
    "surprise":          "😲 Surprised",
    "stress":            "😣 Stressed",
    "anxiety":           "😰 Anxious",
    "anticipation":      "⏳ Expectant",
    "trust":             "🤝 Trusting",

    # ─── Social & cognitive & style ──────────────────────────
    "confidence":        "Confident",
    "friendliness":      "Friendly",
    "empathy":           "Empathetic",
    "engagement":        "Engaged",
    "creativity":        "Creative",
    "precision":         "Precise",
    "humor":             "Humorous",
    "civility":          "Civil",
    "charisma":          "Charismatic",
    "persuasion":        "Persuasive",
    "wit":               "Witty",
    "patience":          "Patient",
    "curiosity":         "Curious",
    "sexual_arousal":    "🔥 Aroused",
    "flirtation":        "Flirty",
    "sarcasm":           "Sarcastic",
    "profanity":         "Profane",
    "aggressiveness":    "Aggressive",
    "confusion":         "Confused",
    "embarrassment":     "Embarrassed",
    "guilt":             "Guilty",

    # ─── Secondary emotions ──────────────────────────────────
    "optimism":          "Optimistic",
    "ecstasy":           "Ecstatic",
    "cheerfulness":      "Cheerful",
    "enthusiasm":        "Enthusiastic",
    "gloom":             "Gloomy",
    "despair":           "Despairing",
    "loneliness":        "Lonely",
    "irritation":        "Irritated",
    "rage":              "Enraged",
    "annoyance":         "Annoyed",
    "apprehension":      "Apprehensive",
    "terror":            "Terrified",
    "panic":             "Panicked",
    "revulsion":         "Revolted",
    "contempt":          "Contemptuous",
    "loathing":          "Loathing",
    "amazement":         "Amazed",
    "astonishment":      "Astonished",
    "startle":           "Startled",
    "acceptance":        "Accepting",
    "admiration":        "Admiring",
    "reliance":          "Reliant",
    "eagerness":         "Eager",
    "vigilance":         "Vigilant",
    "interest":          "Interested",
    "tension":           "Tense",
    "overwhelm":         "Overwhelmed",
    "unease":            "Uneasy",
    "worry":             "Worried",
    "nervousness":       "Nervous",
    "dread":             "Dreading",

    # ─── Tertiary emotions ───────────────────────────────────
    "hope":              "Hopeful",
    "bliss":             "Blissful",
    "merriment":         "Merry",
    "melancholy":        "Melancholic",
    "distress":          "Distressed",
    "isolation":         "Isolated",
    "frustration":       "Frustrated",
    "fury":              "Furious",
    "agitation":         "Agitated",
    "hesitation":        "Hesitant",
    "horror":            "Horrified",
    "alarm":             "Alarmed",
    "abhorrence":        "Abhorrent",
    "scorn":             "Scornful",
    "detestation":       "Detesting",
    "wonder":            "Wonder-struck",
    "bewilderment":      "Bewildered",
    "jolt":              "Jolted",
    "approval":          "Approving",
    "esteem":            "Esteeming",
    "dependence":        "Dependent",
    "zeal":              "Zealous",
    "fervor":            "Fervent",
    "watchfulness":      "Watchful",
    "strain":            "Strained",
    "swamped":           "Swamped",
    "discomfort":        "Uncomfortable",
    "concern":           "Concerned",
    "restlessness":      "Restless",
    "foreboding":        "Foreboding",

    # ─── Dyads ───────────────────────────────────────────────
    "love":              "Loving",
    "submission":        "Submissive",
    "awe":               "Awed",
    "disappointment":    "Disappointed",
    "remorse":           "Remorseful",
    "lust":              "Lustful",
    "intimacy":          "Intimate",
    "interest_driven":   "Intrigued",
    "playfulness":       "Playful",
    "excitement":        "Excited",
    "burnout":           "Burnt-out",
    "exhaustion":        "Exhausted",

    # ─── Triads ──────────────────────────────────────────────
    "lustful_excitement":"Lustfully-Excited",
    "affection":         "Affectionate",
    "creative_collaboration": "Collaborative",
    "inspired_eagerness":"Inspired",
    "euphoria":          "Euphoric",
    "collapse":          "Collapsed",
}
EOF